### ISSUE TITLE
Dishwasher ideas/improvements/todo

### ISSUE THREAD

**Issue by torrottum** [torrottum/home-assistant-config#2]
- [ ] Check with other programs as well. (Eco without turbo, 76c without turbo)
   - [ ] Eco without turbo
   - [ ] 75c without turbo
- [ ] Lift conditions up
    Should be doable with an or condition?
- [ ] Remove debugging automation
